[project]
name = "dyn-gestures"
version = "0.1.0"
description = "基于CVZone和MediaPipe的实时手势检测应用程序"
authors = [
    {name = "Your Name", email = "your.email@example.com"}
]
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "PyQt6",
    "pynput",
    "pywin32",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["dyn_gestures"]
